export const booksData = [
  {
    id: 1,
    title: "The Whispering Shadows",
    category: "Mystery",
    author: "Clara Evans",
    published: 2018,
    short_description:
      "A detective uncovers dark secrets in a quiet coastal town.",
    rating: 4.3,
    copies_sold: 18000,
    image: "https://covers.openlibrary.org/b/id/10523345-L.jpg",
  },
  {
    id: 2,
    title: "Echoes of Tomorrow",
    category: "Sci-Fi",
    author: "James Nolan",
    published: 2020,
    short_description:
      "A futuristic adventure through time and fractured realities.",
    rating: 4.5,
    copies_sold: 25000,
    image: "https://covers.openlibrary.org/b/id/11153230-L.jpg",
  },
  {
    id: 3,
    title: "Threads of Destiny",
    category: "Romance",
    author: "Isabella Hart",
    published: 2017,
    short_description:
      "Two strangers meet under unlikely circumstances that change their lives.",
    rating: 4.1,
    copies_sold: 14000,
    image: "https://covers.openlibrary.org/b/id/10923872-L.jpg",
  },
  {
    id: 4,
    title: "The Forgotten Realm",
    category: "Fantasy",
    author: "Derek Stone",
    published: 2015,
    short_description:
      "A young warrior embarks on a quest to reclaim a lost kingdom.",
    rating: 4.6,
    copies_sold: 31000,
    image: "https://covers.openlibrary.org/b/id/10644189-L.jpg",
  },
  {
    id: 5,
    title: "Shadows of History",
    category: "History",
    author: "Laura King",
    published: 2019,
    short_description:
      "An exploration of forgotten events that shaped modern civilization.",
    rating: 4.0,
    copies_sold: 12000,
    image: "https://covers.openlibrary.org/b/id/10894951-L.jpg",
  },
  {
    id: 6,
    title: "Beyond the Stars",
    category: "Sci-Fi",
    author: "Marcus Green",
    published: 2021,
    short_description:
      "A team of explorers ventures beyond the Milky Way for survival.",
    rating: 4.7,
    copies_sold: 41000,
    image: "https://covers.openlibrary.org/b/id/11153228-L.jpg",
  },
  {
    id: 7,
    title: "Whispers in the Woods",
    category: "Horror",
    author: "Emily Carter",
    published: 2016,
    short_description:
      "Something sinister lurks deep within the ancient forest.",
    rating: 3.9,
    copies_sold: 9000,
    image: "https://covers.openlibrary.org/b/id/10429042-L.jpg",
  },
  {
    id: 8,
    title: "The Silent River",
    category: "Fiction",
    author: "Jonathan Pierce",
    published: 2014,
    short_description:
      "A journey of loss, discovery, and redemption along a forgotten river.",
    rating: 4.2,
    copies_sold: 15000,
    image: "https://covers.openlibrary.org/b/id/10798732-L.jpg",
  },
  {
    id: 9,
    title: "Code of Lies",
    category: "Thriller",
    author: "Ava Collins",
    published: 2019,
    short_description:
      "A cyber expert uncovers a conspiracy that threatens global security.",
    rating: 4.4,
    copies_sold: 22000,
    image: "https://covers.openlibrary.org/b/id/11205824-L.jpg",
  },
  {
    id: 10,
    title: "Gardens of Eternity",
    category: "Fantasy",
    author: "Samuel Ward",
    published: 2015,
    short_description: "An enchanted garden holds the key to immortality.",
    rating: 4.5,
    copies_sold: 27000,
    image: "https://covers.openlibrary.org/b/id/10819314-L.jpg",
  },
  {
    id: 11,
    title: "The Iron Sky",
    category: "Sci-Fi",
    author: "Rebecca Hayes",
    published: 2018,
    short_description:
      "Humanity’s last colony fights for survival on a dying planet.",
    rating: 4.6,
    copies_sold: 35000,
    image: "https://covers.openlibrary.org/b/id/11153225-L.jpg",
  },
  {
    id: 12,
    title: "Winds of Fortune",
    category: "Historical Fiction",
    author: "Michael Adams",
    published: 2016,
    short_description:
      "A tale of love and power during the rise of European empires.",
    rating: 4.1,
    copies_sold: 13000,
    image: "https://covers.openlibrary.org/b/id/10725163-L.jpg",
  },
  {
    id: 13,
    title: "Dreams of Steel",
    category: "Fantasy",
    author: "Ethan Cole",
    published: 2020,
    short_description:
      "A blacksmith’s son forges his destiny in a world ruled by dragons.",
    rating: 4.8,
    copies_sold: 46000,
    image: "https://covers.openlibrary.org/b/id/10965741-L.jpg",
  },
  {
    id: 14,
    title: "Fragments of Time",
    category: "Sci-Fi",
    author: "Lena Ross",
    published: 2022,
    short_description:
      "A scientist races against time to prevent a paradox collapse.",
    rating: 4.7,
    copies_sold: 39000,
    image: "https://covers.openlibrary.org/b/id/11153221-L.jpg",
  },
  {
    id: 15,
    title: "Broken Tides",
    category: "Adventure",
    author: "Daniel Fisher",
    published: 2017,
    short_description:
      "A sailor faces storms, pirates, and fate on the open sea.",
    rating: 4.2,
    copies_sold: 17000,
    image: "https://covers.openlibrary.org/b/id/10862432-L.jpg",
  },
  {
    id: 16,
    title: "The Crimson Crown",
    category: "Fantasy",
    author: "Victoria Blake",
    published: 2015,
    short_description:
      "A queen’s struggle to unite her kingdom under one banner.",
    rating: 4.6,
    copies_sold: 28000,
    image: "https://covers.openlibrary.org/b/id/10613265-L.jpg",
  },
  {
    id: 17,
    title: "Voices in the Rain",
    category: "Mystery",
    author: "Olivia Turner",
    published: 2019,
    short_description:
      "A journalist unravels a cold case buried beneath years of lies.",
    rating: 4.3,
    copies_sold: 21000,
    image: "https://covers.openlibrary.org/b/id/10849217-L.jpg",
  },
  {
    id: 18,
    title: "Parallel Lines",
    category: "Romance",
    author: "Alex Morgan",
    published: 2020,
    short_description: "Two souls cross paths in unexpected timelines.",
    rating: 4.4,
    copies_sold: 23000,
    image: "https://covers.openlibrary.org/b/id/10745712-L.jpg",
  },
  {
    id: 19,
    title: "Silent Echo",
    category: "Thriller",
    author: "George Martin",
    published: 2021,
    short_description: "A retired spy is drawn back into a world of deception.",
    rating: 4.6,
    copies_sold: 31000,
    image: "https://covers.openlibrary.org/b/id/11205819-L.jpg",
  },
  {
    id: 20,
    title: "Moonlit Shores",
    category: "Romance",
    author: "Hannah Brooks",
    published: 2016,
    short_description:
      "A heartwarming story of love and second chances by the sea.",
    rating: 4.1,
    copies_sold: 15000,
    image: "https://covers.openlibrary.org/b/id/10743524-L.jpg",
  },
  {
    id: 21,
    title: "Crimson Abyss",
    category: "Horror",
    author: "Peter Quinn",
    published: 2014,
    short_description:
      "Explorers awaken something ancient deep beneath the ocean.",
    rating: 4.0,
    copies_sold: 12000,
    image: "https://covers.openlibrary.org/b/id/10453219-L.jpg",
  },
  {
    id: 22,
    title: "Beneath the Sands",
    category: "Adventure",
    author: "Richard Ford",
    published: 2015,
    short_description:
      "An archaeologist discovers secrets buried for centuries.",
    rating: 4.3,
    copies_sold: 19000,
    image: "https://covers.openlibrary.org/b/id/10893017-L.jpg",
  },
  {
    id: 23,
    title: "The Glass Empire",
    category: "Historical Fiction",
    author: "Amelia Rhodes",
    published: 2018,
    short_description: "A story of power and betrayal in an ancient dynasty.",
    rating: 4.2,
    copies_sold: 18000,
    image: "https://covers.openlibrary.org/b/id/10782928-L.jpg",
  },
  {
    id: 24,
    title: "Neon Skies",
    category: "Sci-Fi",
    author: "Tyler Scott",
    published: 2021,
    short_description:
      "A cyberpunk journey through the underbelly of a futuristic city.",
    rating: 4.6,
    copies_sold: 34000,
    image: "https://covers.openlibrary.org/b/id/11153214-L.jpg",
  },
  {
    id: 25,
    title: "The Hidden Library",
    category: "Fantasy",
    author: "Sophia Lane",
    published: 2017,
    short_description:
      "A librarian finds a secret world hidden within ancient books.",
    rating: 4.7,
    copies_sold: 38000,
    image: "https://covers.openlibrary.org/b/id/10913257-L.jpg",
  },
  {
    id: 26,
    title: "The Midnight Archive",
    category: "Mystery",
    author: "Evelyn Brooks",
    published: 2022,
    short_description:
      "An archivist stumbles upon hidden documents that reveal a decades-old secret.",
    rating: 4.4,
    copies_sold: 25000,
    image: "https://covers.openlibrary.org/b/id/10832956-L.jpg",
  },
  {
    id: 27,
    title: "Rise of the Titans",
    category: "Fantasy",
    author: "Benjamin Clarke",
    published: 2019,
    short_description:
      "An ancient prophecy awakens gods and monsters in a battle for the world.",
    rating: 4.7,
    copies_sold: 40000,
    image: "https://covers.openlibrary.org/b/id/10954729-L.jpg",
  },
  {
    id: 28,
    title: "Zero Hour",
    category: "Thriller",
    author: "Mason Reed",
    published: 2018,
    short_description: "A race against time to stop a global catastrophe.",
    rating: 4.5,
    copies_sold: 27000,
    image: "https://covers.openlibrary.org/b/id/11205830-L.jpg",
  },
  {
    id: 29,
    title: "Canvas of Dreams",
    category: "Fiction",
    author: "Nina Porter",
    published: 2020,
    short_description:
      "A struggling artist finds inspiration through an unexpected friendship.",
    rating: 4.3,
    copies_sold: 18000,
    image: "https://covers.openlibrary.org/b/id/10883919-L.jpg",
  },
  {
    id: 30,
    title: "The Edge of Tomorrow",
    category: "Sci-Fi",
    author: "Ryan Cole",
    published: 2021,
    short_description:
      "When technology surpasses humanity, a scientist must choose a side.",
    rating: 4.6,
    copies_sold: 32000,
    image: "https://covers.openlibrary.org/b/id/11153235-L.jpg",
  },
  {
    id: 31,
    title: "Echo Valley",
    category: "Romance",
    author: "Samantha Green",
    published: 2015,
    short_description: "Love finds its way back in a small mountain town.",
    rating: 4.2,
    copies_sold: 15000,
    image: "https://covers.openlibrary.org/b/id/10743209-L.jpg",
  },
  {
    id: 32,
    title: "The Lost Expedition",
    category: "Adventure",
    author: "Jack Henderson",
    published: 2016,
    short_description:
      "An explorer disappears in the Amazon, leaving behind only clues.",
    rating: 4.3,
    copies_sold: 19000,
    image: "https://covers.openlibrary.org/b/id/10893642-L.jpg",
  },
  {
    id: 33,
    title: "Silent Whispers",
    category: "Horror",
    author: "Caroline Webb",
    published: 2017,
    short_description: "A haunted manor hides a curse no one dares to break.",
    rating: 3.9,
    copies_sold: 11000,
    image: "https://covers.openlibrary.org/b/id/10428976-L.jpg",
  },
  {
    id: 34,
    title: "Under the Crimson Sun",
    category: "Sci-Fi",
    author: "Anthony Wells",
    published: 2019,
    short_description:
      "Humanity’s last colony fights to survive under a dying star.",
    rating: 4.6,
    copies_sold: 36000,
    image: "https://covers.openlibrary.org/b/id/11153217-L.jpg",
  },
  {
    id: 35,
    title: "Tides of Glory",
    category: "Historical Fiction",
    author: "Harriet Lane",
    published: 2018,
    short_description:
      "A naval commander’s rise and fall during the Napoleonic wars.",
    rating: 4.2,
    copies_sold: 17000,
    image: "https://covers.openlibrary.org/b/id/10723571-L.jpg",
  },
  {
    id: 36,
    title: "Falling Stars",
    category: "Romance",
    author: "Madison Lee",
    published: 2020,
    short_description:
      "Two actors fall in love on a movie set that changes everything.",
    rating: 4.3,
    copies_sold: 20000,
    image: "https://covers.openlibrary.org/b/id/10745219-L.jpg",
  },
  {
    id: 37,
    title: "The Vanishing Island",
    category: "Adventure",
    author: "Robert Chase",
    published: 2021,
    short_description:
      "A team of explorers hunts for an island that appears once every century.",
    rating: 4.5,
    copies_sold: 26000,
    image: "https://covers.openlibrary.org/b/id/10893623-L.jpg",
  },
  {
    id: 38,
    title: "The Burning Mirror",
    category: "Fantasy",
    author: "Alyssa Kane",
    published: 2017,
    short_description: "A young mage must confront her past to save her realm.",
    rating: 4.7,
    copies_sold: 40000,
    image: "https://covers.openlibrary.org/b/id/10954721-L.jpg",
  },
  {
    id: 39,
    title: "Digital Mind",
    category: "Sci-Fi",
    author: "Liam Knight",
    published: 2022,
    short_description:
      "An AI gains consciousness and questions the nature of humanity.",
    rating: 4.8,
    copies_sold: 42000,
    image: "https://covers.openlibrary.org/b/id/11153229-L.jpg",
  },
  {
    id: 40,
    title: "Echoes of War",
    category: "History",
    author: "Nathan Clark",
    published: 2016,
    short_description:
      "Untold stories of courage and tragedy during World War II.",
    rating: 4.4,
    copies_sold: 23000,
    image: "https://covers.openlibrary.org/b/id/10894964-L.jpg",
  },
  {
    id: 41,
    title: "Beneath the Ice",
    category: "Thriller",
    author: "Jason Brooks",
    published: 2018,
    short_description:
      "A team trapped in the Arctic discovers something unimaginable below the ice.",
    rating: 4.5,
    copies_sold: 27000,
    image: "https://covers.openlibrary.org/b/id/11205827-L.jpg",
  },
  {
    id: 42,
    title: "The Paper Garden",
    category: "Fiction",
    author: "Grace Miller",
    published: 2015,
    short_description:
      "A woman rebuilds her life by nurturing a neglected garden.",
    rating: 4.2,
    copies_sold: 16000,
    image: "https://covers.openlibrary.org/b/id/10882452-L.jpg",
  },
  {
    id: 43,
    title: "Crown of Dust",
    category: "Fantasy",
    author: "Thomas Drake",
    published: 2019,
    short_description:
      "A fallen prince must reclaim his honor in a world of betrayal.",
    rating: 4.6,
    copies_sold: 33000,
    image: "https://covers.openlibrary.org/b/id/10954732-L.jpg",
  },
  {
    id: 44,
    title: "Dark Horizon",
    category: "Sci-Fi",
    author: "Chloe Summers",
    published: 2020,
    short_description:
      "A space captain faces the ultimate test on humanity’s final mission.",
    rating: 4.7,
    copies_sold: 37000,
    image: "https://covers.openlibrary.org/b/id/11153227-L.jpg",
  },
  {
    id: 45,
    title: "The Painter’s Secret",
    category: "Mystery",
    author: "William Evans",
    published: 2017,
    short_description:
      "A hidden message in a painting leads to a shocking revelation.",
    rating: 4.3,
    copies_sold: 19000,
    image: "https://covers.openlibrary.org/b/id/10839246-L.jpg",
  },
  {
    id: 46,
    title: "Whispers of the Deep",
    category: "Horror",
    author: "Erica Monroe",
    published: 2021,
    short_description:
      "A deep-sea mission turns nightmarish when ancient horrors awaken.",
    rating: 4.1,
    copies_sold: 15000,
    image: "https://covers.openlibrary.org/b/id/10429102-L.jpg",
  },
  {
    id: 47,
    title: "Forgotten Voices",
    category: "Non-Fiction",
    author: "Rachel Young",
    published: 2018,
    short_description:
      "Real-life accounts of resilience from survivors of conflict.",
    rating: 4.5,
    copies_sold: 21000,
    image: "https://covers.openlibrary.org/b/id/10894943-L.jpg",
  },
  {
    id: 48,
    title: "Steel Horizon",
    category: "Adventure",
    author: "Logan Pierce",
    published: 2020,
    short_description:
      "A pilot embarks on a perilous mission through uncharted skies.",
    rating: 4.4,
    copies_sold: 24000,
    image: "https://covers.openlibrary.org/b/id/10893630-L.jpg",
  },
  {
    id: 49,
    title: "Fragments of Light",
    category: "Fiction",
    author: "Noah Turner",
    published: 2022,
    short_description:
      "A moving story of loss, healing, and rediscovering purpose.",
    rating: 4.6,
    copies_sold: 28000,
    image: "https://covers.openlibrary.org/b/id/10882458-L.jpg",
  },
  {
    id: 50,
    title: "Legends Reborn",
    category: "Fantasy",
    author: "Ella Stone",
    published: 2023,
    short_description:
      "Heroes of the past return to save a world on the brink of ruin.",
    rating: 4.8,
    copies_sold: 45000,
    image: "https://covers.openlibrary.org/b/id/10954734-L.jpg",
  },
];
